version: '3'
services:
  app:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb+srv://Mauricio:1990@cluster0.xzxeagl.mongodb.net/?retryWrites=true&w=majority
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
